import './styles/main.scss';
import styles from './layout.module.scss';
import type { Metadata } from 'next';
import { Providers } from './GlobalRedux/provider';
import { Header } from './components/Header/Header';
import { ProgressBar } from './components/ProgressBar/ProgressBar';
import { PhoneHeader } from './components/PhoneHeader/PhoneHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={styles.html}
    >
      <body className={styles.body}>
        <Providers>
          {<PhoneHeader />}
          {<Header />}
          {<ProgressBar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
